/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.InsertController;
import static com.oracle.jrockit.jfr.ContentType.Address;
import javax.swing.JOptionPane;

/**
 *
 
 */
public class Channelling extends javax.swing.JFrame {

    /**
     * Creates new form Channelling
     */
    public Channelling() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CTime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CClinicCMB = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CDtate = new javax.swing.JTextField();
        CNIC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        SubmitBtn = new javax.swing.JButton();
        AmountTF = new javax.swing.JTextField();
        ResetBtn = new javax.swing.JButton();
        PrintBtn = new javax.swing.JButton();
        HomeBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Channelling");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Name.setText("Name :");
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 70, -1));
        getContentPane().add(NameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 200, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("NIC :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 40, -1));
        getContentPane().add(CTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 200, 35));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Clinic :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 60, -1));

        CClinicCMB.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        CClinicCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Eye Clinic", "Dental Clinic", "Dermatology Clinic", "Physiotherapy and Orthopedic Clinic" }));
        CClinicCMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CClinicCMBActionPerformed(evt);
            }
        });
        getContentPane().add(CClinicCMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 200, 29));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Date :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 60, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Time :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 50, -1));
        getContentPane().add(CDtate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 200, 35));
        getContentPane().add(CNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 200, 35));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Amount :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 80, -1));

        SubmitBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SubmitBtn.setText("Submit");
        SubmitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitBtnMouseClicked(evt);
            }
        });
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, -1, -1));
        getContentPane().add(AmountTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 200, 29));

        ResetBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ResetBtn.setText("Reset");
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ResetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 65, -1));

        PrintBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PrintBtn.setText("Print");
        PrintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintBtnActionPerformed(evt);
            }
        });
        getContentPane().add(PrintBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 63, -1));

        HomeBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HomeBtn.setText("HOME");
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(HomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/Home02.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        // TODO add your handling code here:.
         ReceptionHome back = new ReceptionHome();
        back.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_HomeBtnActionPerformed
        public void clearField() {
        NameTF.setText("");
        CNIC.setText("");
        CClinicCMB.setSelectedItem(0);
        CDtate.setText("");
        CTime.setText("");
        AmountTF.setText("");   
    }
        
    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        // TODO add your handling code here:
         clearField();
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        // TODO add your handling code here:
        String Clinic = CClinicCMB.getSelectedItem().toString();
        
        InsertController.InsertChannelling(NameTF.getText(),CNIC.getText(),Clinic,CDtate.getText(),CTime.getText(),AmountTF.getText());    
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void PrintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Bill is being printed", " Payment Succesfull",JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_PrintBtnActionPerformed

    private void SubmitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitBtnMouseClicked

    private void CClinicCMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CClinicCMBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CClinicCMBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Channelling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Channelling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Channelling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Channelling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Channelling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AmountTF;
    private javax.swing.JComboBox<String> CClinicCMB;
    private javax.swing.JTextField CDtate;
    private javax.swing.JTextField CNIC;
    private javax.swing.JTextField CTime;
    private javax.swing.JButton HomeBtn;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField NameTF;
    private javax.swing.JButton PrintBtn;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
