/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.InsertController;
import javax.swing.JLabel;

/**
 *
 * @author Iresh
 */
public class DoctorTreatment extends javax.swing.JFrame {

    /**
     * Creates new form DoctorTreatment
     */
    public DoctorTreatment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DoTr = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DoNi = new javax.swing.JTextField();
        DoDa = new javax.swing.JTextField();
        DoTi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        DoTre = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        DoMe = new javax.swing.JLabel();
        DoBa = new javax.swing.JButton();
        DtSE = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DoTr.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        DoTr.setText("Doctor Treatments");
        DoTr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DoTrMouseClicked(evt);
            }
        });
        getContentPane().add(DoTr, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 25, 231, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("NIC");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 86, 62, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("DATE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 86, 64, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("TIme");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 86, 80, -1));

        DoNi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoNiActionPerformed(evt);
            }
        });
        getContentPane().add(DoNi, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 126, 110, -1));

        DoDa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoDaActionPerformed(evt);
            }
        });
        getContentPane().add(DoDa, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 126, 88, -1));
        getContentPane().add(DoTi, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 126, 61, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 200, 271, 311));

        DoTre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DoTre.setText("Treatment");
        getContentPane().add(DoTre, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 164, 121, 30));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 263, 311));

        DoMe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DoMe.setText("Medicines");
        getContentPane().add(DoMe, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 164, 161, 30));

        DoBa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DoBa.setText("Back");
        DoBa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoBaActionPerformed(evt);
            }
        });
        getContentPane().add(DoBa, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 25, -1, -1));

        DtSE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DtSE.setText("Send");
        DtSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DtSEActionPerformed(evt);
            }
        });
        getContentPane().add(DtSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 488, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/Home02.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DoNiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoNiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoNiActionPerformed

    private void DoDaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoDaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoDaActionPerformed

    private void DoBaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoBaActionPerformed
        // TODO add your handling code here:
        DoctorHome back = new DoctorHome();
        back.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_DoBaActionPerformed

    private void DoTrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoTrMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DoTrMouseClicked

    private void DtSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DtSEActionPerformed
        
    }//GEN-LAST:event_DtSEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorTreatment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DoBa;
    private javax.swing.JTextField DoDa;
    private javax.swing.JLabel DoMe;
    private javax.swing.JTextField DoNi;
    private javax.swing.JTextField DoTi;
    private javax.swing.JLabel DoTr;
    private javax.swing.JLabel DoTre;
    private javax.swing.JButton DtSE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
