/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.DBSearch;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class DoctorHome extends javax.swing.JFrame {

    /**
     * Creates new form DoctorHome
     */
    public DoctorHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SearchNIC1 = new javax.swing.JTextField();
        SearchPBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        SearchNIC2 = new javax.swing.JTextField();
        SearchHBtn = new javax.swing.JButton();
        PClinicCMB = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        SearchCBtn = new javax.swing.JButton();
        DLOutBtn = new javax.swing.JButton();
        treat1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Doctor HOME");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 28, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("View Patient Details");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 111, -1, -1));
        jPanel1.add(SearchNIC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 144, 160, -1));

        SearchPBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SearchPBtn.setText("Search");
        SearchPBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchPBtnActionPerformed(evt);
            }
        });
        jPanel1.add(SearchPBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("View Patient History");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 184, -1, -1));
        jPanel1.add(SearchNIC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 217, 160, -1));

        SearchHBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SearchHBtn.setText("Search");
        SearchHBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchHBtnMouseClicked(evt);
            }
        });
        SearchHBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchHBtnActionPerformed(evt);
            }
        });
        jPanel1.add(SearchHBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        PClinicCMB.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        PClinicCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Eye Clinic", "Dental Clinic", "Dermatology Clinic", "Physiotherapy and Orthopedic Clinic" }));
        jPanel1.add(PClinicCMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 316, 160, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Search Clinic Type");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 278, -1, -1));

        SearchCBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SearchCBtn.setText("Search");
        SearchCBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchCBtnMouseClicked(evt);
            }
        });
        SearchCBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCBtnActionPerformed(evt);
            }
        });
        jPanel1.add(SearchCBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        DLOutBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DLOutBtn.setText("Logout");
        DLOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DLOutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(DLOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, -1, -1));

        treat1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        treat1.setText("Treatment");
        treat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treat1ActionPerformed(evt);
            }
        });
        jPanel1.add(treat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 140, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/Home01.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 750, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchPBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchPBtnActionPerformed
        // TODO add your handling code here:
        ResultSet rs = new DBSearch().SearchPatient(SearchNIC1.getText());

        try { 
            if(rs.next() == false){
                JOptionPane.showMessageDialog(this,"Patient Doesn't exist");
            }
            else{
                ViewPatient02 view = new ViewPatient02();
                
                view.PFNameTF.setText(rs.getString("FirstName"));
                view.PLNameTF.setText(rs.getString("LastName"));
                view.PNICTF.setText(rs.getString("NIC"));
                view.PBirthTF.setText(rs.getString("BirthDay"));
                view.GenderTF.setText(rs.getString("Gender"));
                view.BTypeTF.setText(rs.getString("BloodType"));
                view.AddressTF.setText(rs.getString("Address"));
                int tele=rs.getInt("Contact");
                view.PContactTF.setText(String.valueOf(tele));
                
                view.setVisible(true);
            }
            
        } catch (SQLException ex) {
        }
        
    }//GEN-LAST:event_SearchPBtnActionPerformed

    private void DLOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DLOutBtnActionPerformed
        // TODO add your handling code here:
        DoctorLogin back = new DoctorLogin();
        back.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_DLOutBtnActionPerformed

    private void SearchHBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchHBtnActionPerformed
        // TODO add your handling code here:
        ResultSet rs = new DBSearch().SearchHistory(SearchNIC2.getText());
        try{
            if(rs.next() == false){
                JOptionPane.showMessageDialog(this,"Patient has no history");
            }
            else{
                ViewPatientHistory view = new ViewPatientHistory();
                
                view.NameTF.setText(rs.getString("Name"));
                view.NICTF.setText(rs.getString("NIC"));
                DefaultTableModel dtm = (DefaultTableModel)view.ViewHistoryTable.getModel();
                dtm.setRowCount(0);
            
                Vector v;
                while (rs.next()){
                    v = new Vector();
                    v.add(rs.getString("Clinic"));
                    v.add(rs.getString("Date"));
                    v.add(rs.getString("Time"));
                    v.add(rs.getString("Amount"));
                    dtm.addRow(v);
                }
                view.setVisible(true);
            }
        }
        catch(SQLException e){

        }
    }//GEN-LAST:event_SearchHBtnActionPerformed

    private void SearchCBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCBtnActionPerformed
        // TODO add your handling code here:
        String Clinic = PClinicCMB.getSelectedItem().toString();
        
        ResultSet rs = new DBSearch().SearchClinic(Clinic);
        
        try{
            ViewClinicWise view = new ViewClinicWise();
                

            DefaultTableModel dtm = (DefaultTableModel)view.ViewClinicTB.getModel();
            dtm.setRowCount(0);
            
            Vector v;
            while (rs.next()){
                v = new Vector();
                v.add(rs.getString("Name"));
                v.add(rs.getString("NIC"));                
                v.add(rs.getString("Clinic"));
                v.add(rs.getString("Date"));
                v.add(rs.getString("Time"));

                dtm.addRow(v);
            }
            view.setVisible(true);
        }
        catch(SQLException e){

        }
        
    }//GEN-LAST:event_SearchCBtnActionPerformed

    private void treat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treat1ActionPerformed
        // TODO add your handling code here:
         DoctorTreatment Treatment = new DoctorTreatment();
        Treatment.setVisible(true);
        super.dispose();
        
    }//GEN-LAST:event_treat1ActionPerformed

    private void SearchCBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchCBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchCBtnMouseClicked

    private void SearchHBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchHBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchHBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DLOutBtn;
    private javax.swing.JComboBox<String> PClinicCMB;
    private javax.swing.JButton SearchCBtn;
    private javax.swing.JButton SearchHBtn;
    private javax.swing.JTextField SearchNIC1;
    private javax.swing.JTextField SearchNIC2;
    private javax.swing.JButton SearchPBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton treat1;
    // End of variables declaration//GEN-END:variables
}
