/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.LoginController;

/**
 *
 * @author Iresh
 */
public class PharmacyLogin extends javax.swing.JFrame {

    /**
     * Creates new form PharmacyLogin
     */
    public PharmacyLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        Ph = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PhUs = new javax.swing.JTextField();
        PhPs = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        PhLo = new javax.swing.JButton();
        PhCl = new javax.swing.JButton();
        PhRc = new javax.swing.JLabel();
        PhDl = new javax.swing.JLabel();
        PhCr = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ph.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Ph.setText("Pharmacy");
        Ph.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PhMouseClicked(evt);
            }
        });
        getContentPane().add(Ph, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 141, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("User Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 113, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Password :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 113, 20));

        PhUs.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PhUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhUsActionPerformed(evt);
            }
        });
        getContentPane().add(PhUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 175, 32));

        PhPs.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PhPs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhPsActionPerformed(evt);
            }
        });
        getContentPane().add(PhPs, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 175, 33));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Forget Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 123, -1));

        PhLo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        PhLo.setText("Login");
        PhLo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PhLoMouseClicked(evt);
            }
        });
        PhLo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhLoActionPerformed(evt);
            }
        });
        getContentPane().add(PhLo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 75, 39));

        PhCl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        PhCl.setText("Clear");
        PhCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhClActionPerformed(evt);
            }
        });
        getContentPane().add(PhCl, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 75, 39));

        PhRc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        PhRc.setText("Reception Login");
        PhRc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PhRcMouseClicked(evt);
            }
        });
        getContentPane().add(PhRc, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 100, 20));

        PhDl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        PhDl.setText("Doctor Login");
        PhDl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PhDlMouseClicked(evt);
            }
        });
        getContentPane().add(PhDl, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 90, 20));

        PhCr.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        PhCr.setForeground(new java.awt.Color(0, 0, 204));
        PhCr.setText("Create New");
        PhCr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhCrActionPerformed(evt);
            }
        });
        getContentPane().add(PhCr, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 140, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/Login.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PhUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhUsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhUsActionPerformed

    private void PhClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhClActionPerformed
        // TODO add your handling code here:
        PhUs.setText("");
        PhPs.setText("");
    }//GEN-LAST:event_PhClActionPerformed

    private void PhLoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhLoActionPerformed
        // TODO add your handling code here:
        LoginController.PharmacyLogin(PhUs.getText(), PhPs.getText());
       
    }//GEN-LAST:event_PhLoActionPerformed

    private void PhPsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhPsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhPsActionPerformed

    private void PhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PhMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PhMouseClicked

    private void PhRcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PhRcMouseClicked
        // TODO add your handling code here:
         ReceptionLogin login = new ReceptionLogin();
        login.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_PhRcMouseClicked

    private void PhDlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PhDlMouseClicked
        // TODO add your handling code here:
         DoctorLogin login = new DoctorLogin();
        login.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_PhDlMouseClicked

    private void PhCrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhCrActionPerformed
        // TODO add your handling code here:
        AddPharmacy add = new AddPharmacy();
        add.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_PhCrActionPerformed

    private void PhLoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PhLoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PhLoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PharmacyLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PharmacyLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PharmacyLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PharmacyLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PharmacyLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ph;
    private javax.swing.JButton PhCl;
    private javax.swing.JButton PhCr;
    private javax.swing.JLabel PhDl;
    private javax.swing.JButton PhLo;
    private javax.swing.JPasswordField PhPs;
    private javax.swing.JLabel PhRc;
    private javax.swing.JTextField PhUs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    // End of variables declaration//GEN-END:variables
}
