/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.DBSearch;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ReceptionHome extends javax.swing.JFrame {

    /**
     * Creates new form ReceptionHome
     */
    public ReceptionHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RegisterPBtn = new javax.swing.JButton();
        ViewAllDocBtn = new javax.swing.JButton();
        SearchNIC = new javax.swing.JTextField();
        SearchPBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SearchDReg = new javax.swing.JTextField();
        SearchDBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ChannelBtn = new javax.swing.JButton();
        RHLBtn = new javax.swing.JButton();
        ManagePBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("HOME");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 33, 90, -1));

        RegisterPBtn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        RegisterPBtn.setText("Register Patient");
        RegisterPBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterPBtnActionPerformed(evt);
            }
        });
        jPanel1.add(RegisterPBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 175, 40));

        ViewAllDocBtn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ViewAllDocBtn.setText("View All Doctors");
        ViewAllDocBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAllDocBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ViewAllDocBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 139, 137, 40));
        jPanel1.add(SearchNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 175, 35));

        SearchPBtn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        SearchPBtn.setText("Search");
        SearchPBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchPBtnActionPerformed(evt);
            }
        });
        jPanel1.add(SearchPBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, 35));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Search NIC");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 120, 24));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Patient Details");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Doctor Details");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 107, -1, -1));
        jPanel1.add(SearchDReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 137, 35));

        SearchDBtn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        SearchDBtn.setText("Search");
        SearchDBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchDBtnActionPerformed(evt);
            }
        });
        jPanel1.add(SearchDBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, 35));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Doctor ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, 20));

        ChannelBtn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ChannelBtn.setText("Channelling");
        ChannelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChannelBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ChannelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 175, 30));

        RHLBtn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        RHLBtn.setText("Logout");
        RHLBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RHLBtnActionPerformed(evt);
            }
        });
        jPanel1.add(RHLBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 29, -1, 30));

        ManagePBtn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ManagePBtn.setText("Manage Patient");
        ManagePBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagePBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ManagePBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 175, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton1.setText("Pharmacy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 130, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Add Pharmacy");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/Home02.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void RegisterPBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterPBtnActionPerformed
        // TODO add your handling code here:
        RegisterPatient regis = new RegisterPatient();
        regis.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_RegisterPBtnActionPerformed

    private void ViewAllDocBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAllDocBtnActionPerformed
        // TODO add your handling code here:
        ResultSet rs = new DBSearch().SearchAllDoc();
        try{
            ViewAllDoctors view = new ViewAllDoctors();
            
            DefaultTableModel dtm = (DefaultTableModel)view.ViewAllDTBoc.getModel();
            dtm.setRowCount(0);
            
            Vector v;
            while (rs.next()){
                    v = new Vector();
                    v.add(rs.getString("Name"));
                    v.add(rs.getString("RegNo"));
                    v.add(rs.getString("Eligibility"));
                    v.add(rs.getString("Special"));
                    v.add(rs.getString("Contact"));
                    dtm.addRow(v);
            }
            view.setVisible(true);
            super.dispose();
        }
        catch(SQLException e){  
        }
    }//GEN-LAST:event_ViewAllDocBtnActionPerformed

    private void ChannelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChannelBtnActionPerformed
        // TODO add your handling code here:
        Channelling chanel = new Channelling();
        chanel.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_ChannelBtnActionPerformed

    private void SearchPBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchPBtnActionPerformed
        // TODO add your handling code here:
        ResultSet rs = new DBSearch().SearchPatient(SearchNIC.getText());

        try { 
            if(rs.next() == false){
                JOptionPane.showMessageDialog(this,"Patient Doesn't exist");
            }
            else{
                ViewPatient01 view = new ViewPatient01();
                
                view.PFNameTF.setText(rs.getString("FirstName"));
                view.PLNameTF.setText(rs.getString("LastName"));
                view.PNICTF.setText(rs.getString("NIC"));
                view.PBirthTF.setText(rs.getString("BirthDay"));
                view.GenderTF.setText(rs.getString("Gender"));
                view.BTypeTF.setText(rs.getString("BloodType"));
                view.AddressTF.setText(rs.getString("Address"));
                int tele=rs.getInt("Contact");
                view.PContactTF.setText(String.valueOf(tele));
                
                view.setVisible(true);
            }
            
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_SearchPBtnActionPerformed

    private void SearchDBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchDBtnActionPerformed
        // TODO add your handling code here:
        ResultSet rs = new DBSearch().SearchDoctor(SearchDReg.getText());

        try { 
            if(rs.next() == false){
                JOptionPane.showMessageDialog(this,"Doctor Doesn't exist");
            }
            else{
                ViewDoctor view = new ViewDoctor();
                
                view.DName.setText(rs.getString("Name"));
                view.DNIC.setText(rs.getString("NIC"));
                view.DReg.setText(rs.getString("RegNo"));
                view.DEligibility.setText(rs.getString("Eligibility"));
                view.DSpecialTF.setText(rs.getString("Special"));
                int tele=rs.getInt("Contact");
                view.DContactTF.setText(String.valueOf(tele));

                view.setVisible(true);
                super.dispose();
            }
            
        } catch (SQLException ex) {
        }

    }//GEN-LAST:event_SearchDBtnActionPerformed

    private void RHLBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RHLBtnActionPerformed
        // TODO add your handling code here:
         ReceptionLogin back = new ReceptionLogin();
        back.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_RHLBtnActionPerformed

    private void ManagePBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagePBtnActionPerformed
        // TODO add your handling code here:
        EditPatient edit = new EditPatient();
        edit.setVisible(true);
        super.dispose();
    }//GEN-LAST:event_ManagePBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceptionHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceptionHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceptionHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceptionHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceptionHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChannelBtn;
    private javax.swing.JButton ManagePBtn;
    private javax.swing.JButton RHLBtn;
    private javax.swing.JButton RegisterPBtn;
    private javax.swing.JButton SearchDBtn;
    private javax.swing.JTextField SearchDReg;
    private javax.swing.JTextField SearchNIC;
    private javax.swing.JButton SearchPBtn;
    private javax.swing.JButton ViewAllDocBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
