/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.InsertController;

/**
 *
 * @author Nishan Fernando
 */
public class RegisterPatient extends javax.swing.JFrame {

    /**
     * Creates new form RegisterPatient
     */
    public RegisterPatient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        FNameTF = new javax.swing.JTextField();
        LNameTF = new javax.swing.JTextField();
        NICTF = new javax.swing.JTextField();
        DOBTf = new javax.swing.JTextField();
        AddressTF = new javax.swing.JTextField();
        ContactTF = new javax.swing.JTextField();
        SubmitBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();
        ADPHBtn = new javax.swing.JButton();
        PaBl = new javax.swing.JTextField();
        ReGe = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setText("Application");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("First Name :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, 100, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Last Name :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 136, 100, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("NIC :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 50, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Date of Birth :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 120, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Gender :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 80, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Address :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 90, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Contact :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 80, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Blood Type :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 110, -1));
        jPanel2.add(FNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 205, 31));
        jPanel2.add(LNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 205, 30));

        NICTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NICTFActionPerformed(evt);
            }
        });
        jPanel2.add(NICTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 205, 30));
        jPanel2.add(DOBTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 205, 30));
        jPanel2.add(AddressTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 205, 30));
        jPanel2.add(ContactTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 205, 30));

        SubmitBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SubmitBtn.setText("Submit");
        SubmitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitBtnMouseClicked(evt);
            }
        });
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });
        jPanel2.add(SubmitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 433, -1, -1));

        ClearBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ClearBtn.setText("Clear");
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ClearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 433, -1, -1));

        ADPHBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ADPHBtn.setText("HOME");
        ADPHBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADPHBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ADPHBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, -1));

        PaBl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaBlActionPerformed(evt);
            }
        });
        jPanel2.add(PaBl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 200, 30));
        jPanel2.add(ReGe, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 190, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/Home02.jpg"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        // TODO add your handling code here:
     
        
        
        
        InsertController.InsertPatient(FNameTF.getText(),LNameTF.getText(), NICTF.getText(), DOBTf.getText(),ReGe.getText(), AddressTF.getText(), ContactTF.getText(), PaBl.getText() );
        
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void ADPHBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADPHBtnActionPerformed
        // TODO add your handling code here:
        ReceptionHome back = new ReceptionHome();
        back.setVisible(true);
        super.dispose();
        clearField();
    }//GEN-LAST:event_ADPHBtnActionPerformed
            public void clearField() {
        FNameTF.setText("");
        LNameTF.setText("");
        NICTF.setText("");
        ReGe.setText(""); 
        AddressTF.setText("");
        ContactTF.setText("");
        PaBl.setText("");
        
            }
    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        // TODO add your handling code here:
        clearField();
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void PaBlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaBlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaBlActionPerformed

    private void NICTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NICTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NICTFActionPerformed

    private void SubmitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitBtnMouseClicked
        // TODO add your handling code here:
        
        InsertController.InsertPatient(FNameTF.getText(),LNameTF.getText(),NICTF.getText(),DOBTf.getText(),ReGe.getText(),AddressTF.getText(),ContactTF.getText(),PaBl.getText()); 
    }//GEN-LAST:event_SubmitBtnMouseClicked
    
    
     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RegisterPatient().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADPHBtn;
    private javax.swing.JTextField AddressTF;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JTextField ContactTF;
    private javax.swing.JTextField DOBTf;
    private javax.swing.JTextField FNameTF;
    private javax.swing.JTextField LNameTF;
    private javax.swing.JTextField NICTF;
    private javax.swing.JTextField PaBl;
    private javax.swing.JTextField ReGe;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
